POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer  <TOKEN>

{
  "author": "Tester",
  "url": "http://localhost:3001/api/blogs",
  "title": "Blog with logged user"
}